version: "3.8"

services:
  db:
    image: "postgres:latest"
    ports:
      - "3000:5432"
    environment:
      - POSTGRES_DB=project_books
      - POSTGRES_USER=administer
      - POSTGRES_PASSWORD=books

