spring:
  jpa:
    hibernate:
    show-sql: true
    ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/project_books
    username: administer
    password: books
  liquibase:
    change-log: classpath:liquibase/changelog.yml
